// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleScssNamespace {
    export interface IIndexModuleScss {
        active: string;
        container: string;
        double: string;
        headRow: string;
        headText: string;
        headerStyle: string;
        notDouble: string;
        success: string;
        table: string;
        tbody: string;
        td: string;
        th: string;
        thead: string;
        tr: string;
        up: string;
        upIcon: string;
    }
}

declare const IndexModuleScssModule: IndexModuleScssNamespace.IIndexModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IndexModuleScssNamespace.IIndexModuleScss;
};

export = IndexModuleScssModule;
